Email link
RAF-SI-2021/Banka-Back pull request #169
Opened 2022-05-02 22:21 UTC by mrkkvc

2022-05-02 22:23 UTC, vmatovic approved these changes

2022-05-02 23:35 UTC, mrkkvc commented
Cini mi se da se smanjio coverage na testovima..moze li neko da baci pogled?

2022-05-03 19:48 UTC, ivandjordjevic99 requested changes
Dodaj HTML tag da url bude link a ne plain tekst u poruku koja se šalje mail servisu.

2022-05-06 15:50 UTC, ivandjordjevic99 approved these changes

2022-05-10 17:08 UTC, merged